/* eslint-disable import/prefer-default-export */
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const GET_ALL_TASK = 'GET_ALL_TASK';
export const GET_ALL_TASK_SUCCESS = 'GET_ALL_TASK_SUCCESS';
export const GET_ALL_TASK_FAILURE = 'GET_ALL_TASK_FAILURE';

export const SET_SELECTED_FILTER = 'SET_SELECTED_FILTER';
export const SET_SELECTED_TASK = 'SET_SELECTED_TASK';
export const SET_SEARCHED_TITLE = 'SET_SEARCHED_TITLE';

export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';

export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAILURE = 'UPDATE_TASK_FAILURE';

export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';
